<?php

namespace Drupal\demo_custom_elements\Processor;

use Drupal\custom_elements\CustomElement;
use Drupal\custom_elements\CustomElementGeneratorTrait;
use Drupal\custom_elements\Processor\DefaultContentEntityProcessor;
use Drupal\node\NodeInterface;

/**
 * Processor for thunder text paragraphs.
 */
class NodeArticleProcessor extends DefaultContentEntityProcessor {

  use CustomElementGeneratorTrait;

  /**
   * {@inheritdoc}
   */
  public function supports($data, $viewMode) {
    if ($data instanceof NodeInterface && $data->getType() == 'article') {
      return $viewMode == 'full';
    }
  }

  /**
   * {@inheritdoc}
   */
  public function addtoElement($node, CustomElement $element, $viewMode) {
    assert($node instanceof NodeInterface);

    parent::addtoElement($node, $element, $viewMode);
    $element->setTag('node-article');
    if ($node->uid->entity) {
      $element->addCacheableDependency($node->uid->entity);
      $element->setAttribute('author', $node->uid->entity->label());
    }
    // Remove uid slot generated by default.
    $slots = $element->getSlots();
    unset($slots['uid']);
    $element->setSlots($slots);
  }

}
